FROM node:20-alpine

WORKDIR /app

# Копируем зависимости
COPY frontend/package*.json ./

RUN npm install

# Копируем весь проект
COPY frontend/ .

# Открываем порт dev-сервера
EXPOSE 3000

# Запускаем dev сервер
CMD ["npm", "run", "dev", "--", "--host"]